spring.application.name=web-educAlba-backend

# No cargar entidades relacionadas fuera de las transacciones (evita errores de LazyInitializationException
# y fuerza a traer explicitamente los datos relacionados que se necesiten, mejor practica de rendimiento)
spring.jpa.open-in-view=false

# En desarrollo, Hibernate actualiza el esquema automaticamente segun las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ejecuta data.sql tambien con bases de datos externas (por defecto Spring Boot
# solo lo hace con bases de datos embebidas, y nosotros usamos Postgres via Docker)
spring.sql.init.mode=always

# Espera a que Hibernate cree las tablas antes de ejecutar data.sql,
# evitando el error de "la tabla todavia no existe"
spring.jpa.defer-datasource-initialization=true
