spring.application.name=web-educAlba-backend

# No cargar entidades relacionadas fuera de las transacciones (evita errores de LazyInitializationException
# y fuerza a traer explicitamente los datos relacionados que se necesiten, mejor practica de rendimiento)
spring.jpa.open-in-view=false

# En desarrollo, Hibernate actualiza el esquema automaticamente segun las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
